# Generated by Django 4.1.2 on 2022-10-24 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplay_app', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('1', 'Action'), ('2', 'Adventure'), ('3', 'Puzzle'), ('4', 'Strategy'), ('5', 'Sports'), ('6', 'Board/Card Game'), ('7', 'Other')], max_length=15)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5)])),
                ('max_level', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('image_URL', models.URLField()),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
