# Generated by Django 4.1.2 on 2022-10-24 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplay_app', '0003_gamemodel_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
