"""not nullable complaint_id

Revision ID: 424ae513787a
Revises: 9d01d3777267
Create Date: 2023-03-21 17:43:20.808131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424ae513787a'
down_revision = '9d01d3777267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
