# Generated by Django 4.1.2 on 2022-10-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employees_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='level',
        ),
    ]
