# Generated by Django 4.1.2 on 2022-10-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_employees_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='level',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
