# Generated by Django 4.1.2 on 2022-10-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=-1),
        ),
    ]
