# Generated by Django 4.1.2 on 2022-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_employees_is_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.CharField(choices=[('jr.', 'Junior'), ('rg', 'Regular'), ('sr', 'Senior')], max_length=15),
        ),
    ]
