# Generated by Django 4.1.2 on 2022-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_employees_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior')], max_length=15),
        ),
    ]
