# Generated by Django 4.1.2 on 2022-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_employees_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior')], max_length=7, verbose_name='Seniority level:'),
        ),
    ]
