# Generated by Django 4.1.2 on 2022-10-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_extrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='extra_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.extrainfo'),
            preserve_default=False,
        ),
    ]
