# Generated by Django 4.1.2 on 2022-10-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_employees_extra_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.employees')),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='extra_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.extrainfo'),
        ),
    ]
